import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

const $=id=>document.getElementById(id);
const screens=[...document.querySelectorAll('.screen')];
const show=id=>{screens.forEach(s=>s.classList.toggle('active',s.id===id));window.scrollTo(0,0)};

const SPECIALTY={
 sprinter:{label:'Sprinter',center:1200,width:360},miler:{label:'Miler',center:1600,width:430},
 intermediate:{label:'Intermedio',center:2050,width:520},stayer:{label:'Fondista',center:2550,width:650}
};
const JOCKEYS=['V. Janáček','R. Sousa','J. Gelabert','B. Fayos','A. Gutiérrez V.','G. Trolley de Prévaux','J. L. Martínez','E. Corallo','J. Grosjean','R. N. Valle','N. de Julián','I. Melgarejo','A. Werlé','C. Cadel','J. Gómez','D. Sikorova','R. Ramos','J. L. Borrego'];
const horses=[
 ['safaga','Safaga','Asoc. La Toledana–Becares','G. Trolley de Prévaux','intermediate',92,91,95,1900,2450,0x3b251c,'#090b0d','#36d0d4'],
 ['estraunza','Estraunza','Becares','A. Gutiérrez V.','stayer',90,97,92,2250,2800,0x6e3824,'#ef7619','#1f55ad'],
 ['sirjan','Sirjan','Cum Laude Racing','J. Gelabert','stayer',91,99,89,2350,3100,0x4b2d22,'#126244','#ffffff'],
 ['fortun','Fortun','La Toledana','B. Fayos','intermediate',93,92,91,1800,2450,0x5c3320,'#101214','#39c8ca'],
 ['entrecopas','Entre Copas','Cuadra África','J. L. Martínez','stayer',88,100,84,2400,4000,0xa8542d,'#aa2431','#f2d66a'],
 ['amedeo','Amedeo Modigliani','Yeguada Rocío','V. Janáček','miler',98,83,97,1450,1750,0x43271c,'#f4f4ef','#0d5c3d'],
 ['frine','Friné','Duque de Alburquerque','J. Grosjean','stayer',94,95,93,2200,2650,0x6b3826,'#ededeb','#722338'],
 ['espoir','Espoir Avenir (FR)','Alain Maubert','E. Corallo','stayer',96,96,94,2300,2850,0x77706a,'#235a9d','#d53838'],
 ['warofdance','War of Dance','Peques','R. N. Valle','stayer',94,95,93,2350,2600,0x4a2b21,'#f07b26','#12a4a4'],
 ['coetzee','Coetzee','Alex y Sofía','R. N. Valle','stayer',93,95,91,2350,2700,0x593326,'#203d87','#eadc61'],
 ['naranco','Naranco','Yeguada Rocío','V. Janáček','stayer',91,94,89,2200,2600,0x38251e,'#f4f4ef','#0d5c3d'],
 ['tetuan','Tetuan','Yeguada Rocío','V. Janáček','stayer',90,95,88,2200,2800,0x2e201b,'#f4f4ef','#0d5c3d'],
 ['shackleton','Shackleton','Yeguada Rocío','I. Melgarejo','stayer',89,96,86,2300,3000,0x573726,'#f4f4ef','#0d5c3d'],
 ['pamplona','Pamplona','Yeguada Rocío','V. Janáček','stayer',90,94,89,2200,2850,0x503126,'#f4f4ef','#0d5c3d'],
 ['ifnotnow','If Not Now','Yeguada Rocío','V. Janáček','intermediate',92,91,92,1900,2350,0x38231c,'#f4f4ef','#0d5c3d'],
 ['thegame','The Game','Cielo de Madrid','R. Sousa','stayer',92,94,91,2150,2600,0x4c2e24,'#72c9d7','#11181a'],
 ['mediastorm','Media Storm','Best Horse','B. Fayos','stayer',92,95,89,2350,2700,0x6d3e2a,'#17307e','#ffffff'],
 ['elcaney','El Caney','Santa Bárbara','A. Gutiérrez V.','stayer',91,95,89,2300,2800,0x39241d,'#f2d64e','#168154'],
 ['kingjungle','King of Jungle','Yeguada Rocío','V. Janáček','sprinter',99,77,99,1000,1400,0x44291e,'#f4f4ef','#0d5c3d'],
 ['samedi','Samedi Rien','Yeguada Rocío','V. Janáček','miler',96,84,96,1400,1800,0x603627,'#f4f4ef','#0d5c3d']
].map((x,i)=>({id:x[0],name:x[1],stable:x[2],preferredJockey:x[3],specialty:x[4],speed:x[5],stamina:x[6],accel:x[7],best:[x[8],x[9]],coat:x[10],silk:x[11],accent:x[12],number:i+1}));
const races=[
 ['gpm','Gran Premio de Madrid',2500,'Hipódromo de La Zarzuela · Madrid','Fondistas'],['copaoro','Copa de Oro de San Sebastián',2400,'Hipódromo de San Sebastián · Lasarte','Fondistas'],['carudel','Gran Premio Claudio Carudel',1600,'Hipódromo de La Zarzuela · Madrid','Milers'],['roman','Gran Premio Román Martín',2000,'Hipódromo de La Zarzuela · Madrid','Intermedios'],['memorial','Memorial Duque de Toledo',2400,'Hipódromo de La Zarzuela · Madrid','Fondistas'],['hispanidad','Gran Premio de la Hispanidad',1600,'Hipódromo de La Zarzuela · Madrid','Milers'],['villapadierna','Gran Premio Villapadierna · Derby',2400,'Hipódromo de La Zarzuela · Madrid','Fondistas'],['beamonte','Gran Premio Beamonte · Oaks',2400,'Hipódromo de La Zarzuela · Madrid','Fondistas']
].map(x=>({id:x[0],name:x[1],distance:x[2],venue:x[3],favors:x[4]}));
const state={mode:'free',selectedRace:null,selected:new Set(),lastField:[],raceSpeed:1,cameraMode:0};

function fit(h,d){const s=SPECIALTY[h.specialty];let v=.68+.43*Math.exp(-Math.pow((d-s.center)/s.width,2));if(d>=h.best[0]&&d<=h.best[1])v+=.06;const gap=d<h.best[0]?h.best[0]-d:d>h.best[1]?d-h.best[1]:0;v-=Math.min(.16,gap/4200);return THREE.MathUtils.clamp(v,.58,1.15)}
function rating(h,d){const long=THREE.MathUtils.clamp((d-1200)/1800,0,1);return (h.speed*(.52-.18*long)+h.stamina*(.22+.27*long)+h.accel*.26)*fit(h,d)}
function currentRace(){return state.mode==='champ'?state.selectedRace:{id:'free',name:'Carrera Libre',distance:+$('freeDistance').value,venue:'Hipódromo de La Zarzuela · Madrid',favors:'Variable'}}
function silk(h){const stars=h.stable==='Yeguada Rocío';return `<div style="width:30px;height:30px;border-radius:50%;border:2px solid ${h.accent};background:${stars?`radial-gradient(circle at 30% 30%,${h.accent} 0 2px,transparent 2.5px),radial-gradient(circle at 70% 70%,${h.accent} 0 2px,transparent 2.5px),${h.silk}`:`linear-gradient(135deg,${h.silk} 0 48%,${h.accent} 49% 62%,${h.silk} 63%)`}"></div>`}
function renderRaces(){$('raceGrid').innerHTML=races.map(r=>`<article class="race-card ${state.selectedRace?.id===r.id?'selected':''}" data-race="${r.id}"><div class="eyebrow">${r.distance.toLocaleString('es-ES')} m</div><h3>${r.name}</h3><p>${r.venue}</p><div class="race-meta"><span class="pill gold">Favorece ${r.favors}</span></div></article>`).join('');document.querySelectorAll('[data-race]').forEach(c=>c.onclick=()=>{state.selectedRace=races.find(r=>r.id===c.dataset.race);$('chooseRaceBtn').disabled=false;renderRaces()})}
function renderHorses(){const d=currentRace().distance;$('horseGrid').innerHTML=horses.map(h=>{const sel=state.selected.has(h.id),f=Math.round(fit(h,d)*100);return `<article class="horse-card ${sel?'selected':''}" data-horse="${h.id}"><div class="select-mark">${sel?'✓':'+'}</div><div style="display:flex;gap:10px;align-items:center">${silk(h)}<div><div class="horse-number">Nº ${h.number} · ${SPECIALTY[h.specialty].label}</div><h3>${h.name}</h3></div></div><div class="horse-sub">${h.stable}<br>${h.preferredJockey}</div><div class="fitbar"><span style="width:${Math.min(100,f)}%"></span></div><div class="stats"><div>Velocidad<b>${h.speed}</b></div><div>Resistencia<b>${h.stamina}</b></div><div>Aceleración<b>${h.accel}</b></div></div></article>`}).join('');document.querySelectorAll('[data-horse]').forEach(c=>c.onclick=()=>{const id=c.dataset.horse;if(state.selected.has(id))state.selected.delete(id);else if(state.selected.size<12)state.selected.add(id);renderHorses()});renderSummary()}
function renderSummary(){const r=currentRace();$('selectedCount').textContent=state.selected.size;$('confirmBtn').disabled=state.selected.size<6;$('raceSummary').innerHTML=`<b>${r.name}</b><br>${r.distance.toLocaleString('es-ES')} m`;$('selectedList').innerHTML=horses.filter(h=>state.selected.has(h.id)).map(h=>`<div class="selected-item"><b>${h.number}. ${h.name}</b><span>${SPECIALTY[h.specialty].label}</span></div>`).join('')}
function openSelection(mode){state.mode=mode;state.selected.clear();$('selectionModeLabel').textContent=mode==='champ'?'Modo Campeonato':'Carrera Libre';$('freeDistanceControl').style.display=mode==='free'?'flex':'none';renderHorses();show('selectionScreen')}
$('freeBtn').onclick=()=>openSelection('free');$('champBtn').onclick=()=>{state.mode='champ';state.selectedRace=null;$('chooseRaceBtn').disabled=true;renderRaces();show('championshipMenu')};$('chooseRaceBtn').onclick=()=>openSelection('champ');document.querySelectorAll('[data-go="mainMenu"]').forEach(b=>b.onclick=()=>show('mainMenu'));$('selectionBack').onclick=()=>show(state.mode==='champ'?'championshipMenu':'mainMenu');$('freeDistance').onchange=renderHorses;$('randomBtn').onclick=()=>{state.selected.clear();[...horses].sort(()=>Math.random()-.5).slice(0,8).forEach(h=>state.selected.add(h.id));renderHorses()};$('bestBtn').onclick=()=>{const d=currentRace().distance;state.selected.clear();[...horses].sort((a,b)=>rating(b,d)-rating(a,d)).slice(0,10).forEach(h=>state.selected.add(h.id));renderHorses()};

let scene,camera,renderer,horseSource,horseClip,worldBuilt=false,raf=0,last=0,runners=[],race=null,running=false,finished=false,startTime=0,elapsed=0,finishOrder=[],snapshot='';
const host=$('webglHost'),RX=105,RZ=62,LAP=1800,FINISH=0;
const loader=new GLTFLoader();
function point(angle,lane=0){const x=(RX+lane)*Math.cos(angle),z=(RZ+lane)*Math.sin(angle);return new THREE.Vector3(x,0,z)}
function tangent(angle){return new THREE.Vector3(-RX*Math.sin(angle),0,RZ*Math.cos(angle)).normalize()}
function normal(angle){const p=point(angle);return new THREE.Vector3(p.x,0,p.z).normalize()}
async function init3D(){if(renderer)return;scene=new THREE.Scene();scene.background=new THREE.Color(0x9fcbe3);scene.fog=new THREE.Fog(0x9fcbe3,120,380);camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,900);renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;host.innerHTML='';host.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x587157,1.8));const sun=new THREE.DirectionalLight(0xfff0d0,3);sun.position.set(-100,140,80);sun.castShadow=true;scene.add(sun);buildWorld();$('loadText').textContent='Cargando caballo animado Three.js…';await new Promise((res,rej)=>loader.load('https://threejs.org/examples/models/gltf/Horse.glb',g=>{horseSource=g.scene;horseClip=g.animations[0];horseSource.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});res()},undefined,rej));$('loadOverlay').classList.add('hidden');addEventListener('resize',()=>{if(!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})}
function buildWorld(){if(worldBuilt)return;worldBuilt=true;const grass=new THREE.MeshStandardMaterial({color:0x397d4e,roughness:.95});const ground=new THREE.Mesh(new THREE.CircleGeometry(300,96),grass);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);const track=new THREE.Mesh(new THREE.RingGeometry(47,68,128),new THREE.MeshStandardMaterial({color:0x57935c,roughness:1}));track.scale.set(RX/68,1,RZ/68);track.rotation.x=-Math.PI/2;track.position.y=.02;track.receiveShadow=true;scene.add(track);for(const lane of [-9,9]){const pts=[];for(let i=0;i<=160;i++)pts.push(point(i/160*Math.PI*2,lane).setY(.65));const rail=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts,true),320,.09,6,true),new THREE.MeshStandardMaterial({color:0xf8f8f4,roughness:.5}));scene.add(rail)}const stand=new THREE.Group();for(let i=0;i<5;i++){const tier=new THREE.Mesh(new THREE.BoxGeometry(70,2,6),new THREE.MeshStandardMaterial({color:i%2?0xcac5b8:0xe7e2d5}));tier.position.set(0,1+i*2,-90-i*4);stand.add(tier)}scene.add(stand);for(let i=0;i<90;i++){const tree=new THREE.Mesh(new THREE.SphereGeometry(1.5+Math.random(),7,6),new THREE.MeshStandardMaterial({color:0x245d39}));const a=Math.random()*Math.PI*2,r=150+Math.random()*80;tree.position.set(Math.cos(a)*r,2,Math.sin(a)*r);scene.add(tree)}}
function assignJockeys(field){const used=new Set();return field.map(h=>{let j=h.preferredJockey;if(used.has(j))j=JOCKEYS.find(x=>!used.has(x))||j;used.add(j);return {...h,assignedJockey:j}})}
function jockeyModel(h){const g=new THREE.Group(),cloth=new THREE.MeshStandardMaterial({color:h.silk,roughness:.65}),accent=new THREE.MeshStandardMaterial({color:h.accent,roughness:.65}),skin=new THREE.MeshStandardMaterial({color:0xc68f6d,roughness:.75}),dark=new THREE.MeshStandardMaterial({color:0x1c2022,roughness:.8});const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.22,.45,5,9),cloth);torso.position.y=1.05;torso.rotation.z=-.36;g.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(.15,12,8),skin);head.position.set(.28,1.34,0);g.add(head);const cap=new THREE.Mesh(new THREE.SphereGeometry(.165,12,6,0,Math.PI*2,0,Math.PI*.58),accent);cap.position.set(.28,1.43,0);g.add(cap);for(const s of [-1,1]){const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.07,.45,4,7),dark);leg.position.set(-.05,.62,s*.18);leg.rotation.z=.55;g.add(leg);const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.055,.38,4,7),cloth);arm.position.set(.32,1.02,s*.20);arm.rotation.z=-.75;g.add(arm)}g.scale.setScalar(1.2);return g}
function recolor(root,color){root.traverse(o=>{if(o.isMesh){o.material=o.material.clone();if(o.material.color)o.material.color.setHex(color);o.castShadow=true;o.receiveShadow=true}})}
async function startRace(field,r){await init3D();cancelAnimationFrame(raf);runners.forEach(x=>{scene.remove(x.root);x.mixer?.stopAllAction()});runners=[];race=r;finished=false;running=false;elapsed=0;finishOrder=[];snapshot='';state.raceSpeed=1;state.cameraMode=0;$('speedBtn').textContent='x1';$('cameraBtn').textContent='Cámara TV';$('finishFlash').classList.remove('show');$('tvRaceTitle').textContent=r.name.toUpperCase();$('tvVenue').textContent=r.venue;const assigned=assignJockeys(field);const startAngle=FINISH-(r.distance/LAP)*Math.PI*2;assigned.forEach((h,i)=>{const root=horseSource.clone(true);recolor(root,h.coat);root.scale.setScalar(.013);root.rotation.y=Math.PI/2;const jm=jockeyModel(h);jm.position.set(0,1.7,0);root.add(jm);scene.add(root);const mixer=new THREE.AnimationMixer(root);const act=mixer.clipAction(horseClip);act.setDuration(.72+Math.random()*.08).play();runners.push({horse:h,root,mixer,action:act,distance:0,speed:0,lateral:(i-(assigned.length-1)/2)*.85,target:0,energy:1,finished:false,time:null,form:.97+Math.random()*.06,phase:Math.random()*6.28})});state.lastField=field;show('raceScreen');$('loadOverlay').classList.add('hidden');startTime=performance.now();last=performance.now();requestAnimationFrame(loop);function route(rn){const a=startAngle+(rn.distance/LAP)*Math.PI*2;const p=point(a,rn.lateral),t=tangent(a);rn.root.position.copy(p);rn.root.rotation.y=Math.atan2(t.x,t.z);return a}}
function targetSpeed(x){const d=race.distance,p=x.distance/d,remaining=d-x.distance,h=x.horse,f=fit(h,d),long=THREE.MathUtils.clamp((d-1400)/1600,0,1);let base=15.5+(h.speed-80)*.12;base*=f*x.form;let drain=(.014+.014*long)*(1+(100-h.stamina)/28);if(h.specialty==='sprinter'&&d>2000)drain*=1.7;if(h.specialty==='stayer'&&d<1600)base*=.91;x.energy=Math.max(0,x.energy-drain*.016*state.raceSpeed);base*=.82+.18*x.energy;if(remaining<450)base*=1+(h.accel-80)/250*(1-remaining/450);base*=1+Math.sin(elapsed*.8+x.phase)*.006;return base}
function loop(now){const dt=Math.min(.04,(now-last)/1000||.016);last=now;const since=(now-startTime)/1000;if(since<3){$('countdown').textContent=3-Math.floor(since)}else{if(!running){running=true;$('countdown').textContent='';$('commentary').textContent='¡Se abren los cajones! Comienza la carrera.'}elapsed+=dt*state.raceSpeed;runners.forEach(x=>{if(x.finished)return;const ts=targetSpeed(x),response=1-Math.exp(-(2+x.horse.accel*.012)*dt*state.raceSpeed);x.speed=THREE.MathUtils.lerp(x.speed,ts,response);x.distance+=x.speed*dt*state.raceSpeed;if(x.distance>=race.distance){x.distance=race.distance;x.finished=true;x.time=elapsed;finishOrder.push(x);if(finishOrder.length===1){snapshot=renderer.domElement.toDataURL('image/jpeg',.8);$('finishFlash').classList.add('show')}}const a=startAngle+(x.distance/LAP)*Math.PI*2,p=point(a,x.lateral),t=tangent(a);x.root.position.copy(p);x.root.rotation.y=Math.atan2(t.x,t.z);x.mixer.update(dt*state.raceSpeed*(.85+x.speed/20));});if(finishOrder.length===runners.length){finished=true;setTimeout(results,650)}}updateCamera(dt,startAngle);updateRank();renderer.render(scene,camera);if(!finished)raf=requestAnimationFrame(loop)}
function sorted(){return [...runners].sort((a,b)=>b.distance-a.distance||(a.time??999)-(b.time??999))}
function updateRank(){if(!race)return;const s=sorted(),lead=s[0];$('metersLeft').textContent=`${Math.max(0,Math.ceil(race.distance-lead.distance)).toLocaleString('es-ES')} m`;$('rankingRows').innerHTML=s.map((x,i)=>`<div class="rank-row"><div class="rank-pos">${i+1}</div><div class="rank-name"><b>${x.horse.name}</b><span>${x.horse.assignedJockey}</span></div><div class="rank-gap">${i?`-${Math.max(0,lead.distance-x.distance).toFixed(1)} m`:'LÍDER'}</div></div>`).join('');if(race.distance-lead.distance<800)$('commentary').textContent=race.distance-lead.distance<250?'¡Últimos 250 metros! Todo se decide al remate.':'Entran en la fase decisiva. Los fondistas intentan imponer su resistencia.'}
function updateCamera(dt,startAngle){if(!runners.length)return;const s=sorted(),lead=s[0],a=startAngle+(lead.distance/LAP)*Math.PI*2,p=point(a),t=tangent(a),n=normal(a);let pos,look=p.clone();if(state.cameraMode===0){pos=p.clone().add(n.multiplyScalar(30)).sub(t.clone().multiplyScalar(10));pos.y=10;look.y=1.5}else if(state.cameraMode===1){pos=p.clone();pos.y=55;look.y=0}else if(state.cameraMode===2){pos=p.clone().add(n.multiplyScalar(15)).sub(t.multiplyScalar(3));pos.y=4;look.add(t.multiplyScalar(8));look.y=1.4}else{pos=point(0,20);pos.y=7;look=point(0);look.y=1.5}camera.position.lerp(pos,1-Math.exp(-3.8*dt));camera.lookAt(look)}
function results(){const rr=[...finishOrder];$('resultTitle').textContent=race.name;$('resultSubtitle').textContent=`${race.distance.toLocaleString('es-ES')} m · ${race.venue}`;$('photoFinish').src=snapshot;const w=rr[0]?.time||0;$('podium').innerHTML=rr.slice(0,3).map((x,i)=>`<div class="podium-card"><span>${i+1}º</span><b>${x.horse.name}</b><small>${x.horse.assignedJockey}</small></div>`).join('');$('classification').innerHTML=rr.map((x,i)=>`<div class="class-row"><strong>${i+1}º</strong><div><b>${x.horse.name}</b><br><span>${x.horse.stable}</span></div><span>${x.horse.assignedJockey}</span><b>${i?`+${(x.time-w).toFixed(2)}s`:x.time.toFixed(2)+'s'}</b></div>`).join('');show('resultsScreen')}
$('confirmBtn').onclick=()=>{const f=horses.filter(h=>state.selected.has(h.id));if(f.length>=6)startRace(f,currentRace())};$('speedBtn').onclick=()=>{state.raceSpeed=state.raceSpeed===1?1.5:state.raceSpeed===1.5?2:1;$('speedBtn').textContent='x'+state.raceSpeed};$('cameraBtn').onclick=()=>{state.cameraMode=(state.cameraMode+1)%4;$('cameraBtn').textContent=['Cámara TV','Cámara aérea','Cámara rail','Cámara meta'][state.cameraMode]};$('exitRaceBtn').onclick=()=>{cancelAnimationFrame(raf);show('mainMenu')};$('menuFromResults').onclick=()=>show('mainMenu');$('repeatBtn').onclick=()=>startRace(state.lastField,currentRace());$('anotherBtn').onclick=()=>show(state.mode==='champ'?'championshipMenu':'selectionScreen');
renderRaces();renderHorses();